# Generated by Django 3.2.9 on 2021-11-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0002_auto_20211115_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='images',
        ),
    ]
